//>>built
require({cache:{"JBrowse/Plugin":function(){define("JBrowse/Plugin",["dojo/_base/declare","JBrowse/Component"],function(h,b){return h(b,{constructor:function(b){this.name=b.name;this.cssLoaded=b.cssLoaded;this._finalizeConfig(b.config)},_defaultConfig:function(){return{baseUrl:"/plugins/"+this.name}}})})},"RegexSequenceSearch/View/SearchSeqDialog":function(){define("dojo/_base/declare,dojo/dom-construct,dojo/aspect,dijit/focus,dijit/form/Button,dijit/form/CheckBox,dijit/form/TextBox,JBrowse/View/Dialog/WithActionBar".split(","),
function(h,b,l,j,m,d,f,n){return h(n,{constructor:function(){var a=this;l.after(this,"hide",function(){j.curNode&&j.curNode.blur();setTimeout(function(){a.destroyRecursive()},500)})},_dialogContent:function(){var a=this.content={},g=b.create("div",{className:"search-dialog"});b.create("div",{className:"search-dialog intro",innerHTML:"This tool creates tracks showing regions of the reference sequence (or its translations) that match a given DNA or amino acid sequence."},g);var c=b.create("div",{className:"section"},
g);b.create("span",{className:"header",innerHTML:"Search for"},c);a.searchBox=new f({});c.appendChild(a.searchBox.domNode);var c=b.create("div",{className:"section"},g),e=b.create("div",{className:"checkboxdiv"},c);a.caseIgnore=new d({label:"Ignore case",id:"search_ignore_case",checked:!0});e.appendChild(a.caseIgnore.domNode);b.create("label",{"for":"search_ignore_case",innerHTML:"Ignore Case"},e);e=b.create("div",{className:"checkboxdiv"},c);a.translate=new d({label:"Translate sequence before searching",
id:"search_translate_first"});e.appendChild(a.translate.domNode);b.create("label",{"for":"search_translate_first",innerHTML:"Translate sequence before searching"},e);c=b.create("div",{className:"checkboxdiv"},c);a.regex=new d({label:"Treat as regular expression",id:"search_as_regex"});c.appendChild(a.regex.domNode);b.create("label",{"for":"search_as_regex",innerHTML:"Treat as regular expression"},c);c=b.create("div",{className:"section"},g);b.create("span",{className:"header",innerHTML:"Search strands"},
c);e=b.create("div",{className:"checkboxdiv"});a.fwdStrand=new d({id:"search_fwdstrand",checked:!0});var k=b.create("div",{className:"checkboxdiv"});a.revStrand=new d({id:"search_revstrand",checked:!0});e.appendChild(a.fwdStrand.domNode);b.create("label",{"for":"search_fwdstrand",innerHTML:"Forward"},e);k.appendChild(a.revStrand.domNode);b.create("label",{"for":"search_revstrand",innerHTML:"Reverse"},k);c.appendChild(e);c.appendChild(k);return g},_getSearchParams:function(){var a=this.content;return{expr:a.searchBox.get("value"),
regex:a.regex.checked,caseIgnore:a.caseIgnore.checked,translate:a.translate.checked,fwdStrand:a.fwdStrand.checked,revStrand:a.revStrand.checked,maxLen:100}},_fillActionBar:function(a){var b=this;(new m({label:"Search",iconClass:"dijitIconBookmark",onClick:function(){var a=b._getSearchParams();b.callback(a);b.hide()}})).placeAt(a);(new m({label:"Cancel",iconClass:"dijitIconDelete",onClick:function(){b.callback(!1);b.hide()}})).placeAt(a)},show:function(a){this.callback=a||function(){};this.set("title",
"Add sequence search track");this.set("content",this._dialogContent());this.inherited(arguments);j.focus(this.closeButtonNode)}})})},"RegexSequenceSearch/Store/SeqFeature/RegexSearch":function(){define("dojo/_base/declare,dojo/_base/array,dojo/_base/lang,JBrowse/Store/SeqFeature,JBrowse/Model/SimpleFeature,JBrowse/Errors,JBrowse/Util,JBrowse/CodonTable".split(","),function(h,b,l,j,m,d,f,n){return h(j,{constructor:function(a){this.searchParams=a.searchParams},_defaultConfig:function(){return f.deepUpdate(dojo.clone(this.inherited(arguments)),
{regionSizeLimit:2E5})},getFeatures:function(a,b,c,e){var k=l.mixin({orig:{start:a.start,end:a.end}},this.searchParams,a.searchParams);if(a.end-a.start>this.config.regionSizeLimit)throw new d.DataOverflow("Region too large to search");var i=this;this.browser.getStore("refseqs",function(o){o?o.getReferenceSequence(a,function(e){i.doSearch(a,e,k,b);c()},e):c()})},doSearch:function(a,g,c,e){var k=RegExp(c.regex?c.expr:this.escapeString(c.expr),c.caseIgnore?"gi":"g"),i=[];c.fwdStrand&&i.push([g,1]);c.revStrand&&
i.push([f.revcom(g),-1]);b.forEach(i,function(b){if(c.translate)for(var g=0;3>g;g++)this._searchSequence(a,b[0],k,b[1],e,!0,g);else this._searchSequence(a,b[0],k,b[1],e)},this)},_searchSequence:function(a,b,c,e,k,i,f){i&&(b=this.translateSequence(b,f));for(var f=f||0,i=i?3:1,n=a.start,a=a.end,d;null!==(d=c.exec(b))&&d.length;){c.lastIndex=d.index+1;var h=d[0],j=0<e?n+f+i*d.index:a-f-i*(d.index+h.length),l=0<e?n+f+i*(d.index+h.length):a-f-i*d.index,h=new m({data:{start:j,end:l,searchMatch:h,strand:e},
id:[j,l,h].join()});k(h)}},translateSequence:function(a,b){for(var c=a.slice(b),c=c.slice(0,3*Math.floor(c.length/3)),e="",f=0;f<c.length;f+=3)var d=c.slice(f,f+3),e=e+n[d];return e},escapeString:function(a){return(a+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")}})})}}});
define("RegexSequenceSearch/main","dojo/_base/declare,dojo/_base/lang,dojo/Deferred,dijit/MenuItem,JBrowse/Plugin,./View/SearchSeqDialog".split(","),function(h,b,l,j,m,d){return h(m,{constructor:function(){this._searchTrackCount=0;this.browser.afterMilestone("initView",function(){this.browser.addGlobalMenuItem("file",new j({label:"Add sequence search track",iconClass:"dijitIconBookmark",onClick:b.hitch(this,"createSearchTrack")}))},this)},createSearchTrack:function(){var b=this;(new d).show(function(d){if(d){var a=
{browser:b.browser,refSeq:b.browser.refSeq,type:"RegexSequenceSearch/Store/SeqFeature/RegexSearch",searchParams:d},g=b.browser.addStoreConfig(void 0,a);a.name=g;d={type:"JBrowse/View/Track/CanvasFeatures",label:"search_track_"+b._searchTrackCount++,key:"Search reference sequence for '"+d.expr+"'",metadata:{category:"Local tracks",Description:"Contains all matches of the text string/regular expression '"+a.searchExpr+"'"},store:g};b.browser.publish("/jbrowse/v1/v/tracks/new",[d]);b.browser.publish("/jbrowse/v1/v/tracks/show",
[d])}})}})});